application: watodoo
version: 3 # Configurable FB post, status bar
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /rest.*
  script: rest.py

- url: /.*
  script: main.py
