application: watodoo
version: ajay
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /feeds/upcoming
  script: feeds/upcoming.py
  login: admin
  
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /.*
  script: main.py
